# Generated by Django 5.2.6 on 2025-09-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HFModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('repo_id', models.CharField(max_length=200)),
                ('backend', models.CharField(choices=[('hf_endpoint', 'HF Inference Endpoint'), ('tgi', 'Text Generation Inference'), ('local', 'Local Transformers')], max_length=20)),
                ('endpoint_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('default_params', models.JSONField(default=dict)),
            ],
        ),
    ]
