# Generated by Django 5.2.6 on 2025-09-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hfmodel',
            name='backend',
            field=models.CharField(choices=[('hf_endpoint', 'HF Inference Endpoint'), ('tgi', 'Text Generation Inference'), ('local', 'Local Transformers'), ('hf_router', 'HF OpenAI-Compatible Router')], max_length=20),
        ),
    ]
