# Generated by Django 5.2.6 on 2025-09-12 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0001_initial'),
        ('models_registry', '0003_alter_hfmodel_backend'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.TextField()),
                ('correctness', models.FloatField()),
                ('relevance', models.FloatField()),
                ('fluency', models.FloatField()),
                ('overall', models.FloatField()),
                ('judge_model', models.CharField(default='mistral:7b', max_length=100)),
                ('prompt_version', models.CharField(default='v1', max_length=20)),
                ('latency_ms', models.IntegerField(default=0)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='ok', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_evals', to='inference.generation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
