# Generated by Django 5.2.6 on 2025-09-20 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0001_initial'),
        ('models_registry', '0004_judgeevaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgeevaluation',
            name='generation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inference.generation'),
        ),
    ]
